In [3]:
'''Importar las librerias usadas para este algoritmo.'''
%matplotlib notebook
from sklearn import metrics
from scipy import stats
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split


In [4]:
'''Carga del dataset con el delimitador punto y coma.'''
df = pd.read_csv('Car_Prices_Dataset.csv', sep=';')

In [5]:
'''Observamos los datos.'''
df.sample(10)

Age      KM  Weight   HP  MetColor      CC  Doors  Price
1277  71.0   74000  1050.0  110         0  1600.0      3   7750
1135  77.0  105152  1015.0   86         0  1300.0      3   6750
435   47.0   78785  1119.0  110         1  1600.0      5  11500
942   58.0   54000  1035.0   86         0  1300.0      5   7350
119   13.0   57037  1115.0  110         0  1600.0      5  18950
1022  65.0   33000  1050.0  110         0  1600.0      3  10450
245   42.0   55968  1050.0  110         0  1600.0      3  11950
616   59.0  144521  1135.0   72         1  2000.0      5   6900
611   59.0  154783  1120.0   72         1  2000.0      3   7750
533   53.0   47451  1055.0  110         1  1600.0      3  12950

In [6]:
'''Analizamos la forma del dataframe, es decir cuantos datos posee, y cuantas columnas.
Para este dataset se tiene un total de 8 caracteristicas y una columna target.'''
df.shape

(1435, 8)

In [7]:
'''Analizamos la forma del dataframe, es decir cuantos datos posee, y cuantas columnas.
Para este dataset se tiene un total de 8 caracteristicas y una columna target.'''
feature_names= ['Age', 'KM', 'Weight', 'HP', 'MetColor', 'CC', 'Doors']
target_name=['Price']
X = df[feature_names].values
y = df[target_name].values

In [8]:
'''Observamos las variables creadas.'''
print(X,y)

[[2.3000e+01 4.6986e+04 1.1650e+03 ... 1.0000e+00 2.0000e+03 3.0000e+00]
 [2.3000e+01 7.2937e+04 1.1650e+03 ... 1.0000e+00 2.0000e+03 3.0000e+00]
 [2.4000e+01 4.1711e+04 1.1650e+03 ... 1.0000e+00 2.0000e+03 3.0000e+00]
 ...
 [7.1000e+01 1.7016e+04 1.0150e+03 ... 0.0000e+00 1.3000e+03 3.0000e+00]
 [7.0000e+01 1.6916e+04 1.0150e+03 ... 1.0000e+00 1.3000e+03 3.0000e+00]
 [7.6000e+01 1.0000e+00 1.1140e+03 ... 0.0000e+00 1.6000e+03 5.0000e+00]] [[13500]
 [13750]
 [13950]
 ...
 [ 8500]
 [ 7250]
 [ 6950]]


In [9]:
'''Estandarización de la data.'''
from sklearn.preprocessing import StandardScaler
VariablesEntradaScaler=StandardScaler()
VariableObjetivoScaler=StandardScaler()

In [10]:
'''Almacenamiento del objeto de ajuste para referencia posterior.'''
VariablesEntradaFit=VariablesEntradaScaler.fit(X)
VariableObjetivoFit=VariableObjetivoScaler.fit(y)

In [11]:
'''Generación de los valores estandarizados de X e y.'''
X=VariablesEntradaFit.transform(X)
y=VariableObjetivoFit.transform(y)

In [ ]:
'''Código que realice la división en entrenamiento y test, de acuerdo con la estretgia de evaluación planeada.'''
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=109)